In [2]:
import numpy as np

In [3]:
mylist= [1,2,3]
x=np.array(mylist)

In [4]:
x

array([1, 2, 3])

In [5]:
y=np.array([4,5,6])
y

array([4, 5, 6])

In [6]:
m=np.array([[7,8,9],[10,11,12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

In [7]:
m.shape


(2, 3)

In [8]:
n=np.arange(0,30,2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [9]:
n=np.arange(0,30,0.5)
n

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. ,
       16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5, 21. , 21.5,
       22. , 22.5, 23. , 23.5, 24. , 24.5, 25. , 25.5, 26. , 26.5, 27. ,
       27.5, 28. , 28.5, 29. , 29.5])

In [10]:
n=n.reshape(5,12)
n

array([[ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
         5.5],
       [ 6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. ,
        11.5],
       [12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. , 16.5, 17. ,
        17.5],
       [18. , 18.5, 19. , 19.5, 20. , 20.5, 21. , 21.5, 22. , 22.5, 23. ,
        23.5],
       [24. , 24.5, 25. , 25.5, 26. , 26.5, 27. , 27.5, 28. , 28.5, 29. ,
        29.5]])

In [11]:
o=np.linspace(0,4,9)

In [12]:
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

np.linespace  devide the span between the first and second number into slices equal to the third number

In [13]:
o.resize(3,3)

In [14]:
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [15]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [16]:
np.ones([3,4], int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [17]:
np.ones([2,4],str)

array([['1', '1', '1', '1'],
       ['1', '1', '1', '1']], dtype='<U1')

In [18]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
y

array([4, 5, 6])

In [21]:
np.diag(y)

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [22]:
np.repeat([1,2,3],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [23]:
p=np.ones([2,3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [24]:
np.vstack([p,p*2])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [25]:
len(np.vstack([p,p*2]))

4

In [26]:
np.hstack([p,p*2])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

#Operations

In [27]:
x

array([1, 2, 3])

In [28]:
y

array([4, 5, 6])

In [29]:
x+y

array([5, 7, 9])

In [30]:
x*y

array([ 4, 10, 18])

In [31]:
z=np.array([y,y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [32]:
z.shape

(2, 3)

In [33]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [34]:
z.T.T

array([[ 4,  5,  6],
       [16, 25, 36]])

In [35]:
z.T.shape

(3, 2)

In [36]:
z.dtype

dtype('int64')

In [37]:
z=z.astype('f')
z.dtype

dtype('float32')

In [38]:
z=z.astype(float)
z

array([[ 4.,  5.,  6.],
       [16., 25., 36.]])

In [39]:
a=np.array([-4,-2,1,3,5])

In [40]:
a.sum()

3

In [41]:
a.max()

5

In [42]:
a.min()

-4

In [43]:
a.mean()

0.6

In [44]:
a.std()

3.2619012860600183

In [45]:
x.dot(y)

32

In [46]:
a.argmax() #give the index of the max number

4

In [47]:
a.argmin() # gives the index of the min number

0

# INDEXING and SLICING

In [48]:
s=np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [49]:
s[0], s[4], s[0:3]

(0, 16, array([0, 1, 4]))

In [50]:
s[-1]

144

In [51]:
s[::-1]

array([144, 121, 100,  81,  64,  49,  36,  25,  16,   9,   4,   1,   0])

In [52]:
s[1:5]

array([ 1,  4,  9, 16])

In [53]:
s[2:6]

array([ 4,  9, 16, 25])

In [54]:
s[-4:] # slice of the last four element of the array

array([ 81, 100, 121, 144])

In [55]:
s[-5:-2]

array([ 64,  81, 100])

In [56]:
r=np.arange(36)
r.resize((6,6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [57]:
r[2,2] #get the value of the second row second column

14

In [58]:
r[3,1:3]

array([19, 20])

In [59]:
r[:2,:-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [60]:
r[:2, :5]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [61]:
r[:-4, :5]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [62]:
r[:-4, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [63]:
r[-1,::2]

array([30, 32, 34])

In [64]:
r[-1,0:6:2]

array([30, 32, 34])

In [65]:
r[r>30]

array([31, 32, 33, 34, 35])

In [66]:
r[r<10]=10
r

array([[10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [67]:
r2=r[:3,:3]
r2

array([[10, 10, 10],
       [10, 10, 10],
       [12, 13, 14]])

In [68]:
r2[:]=0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [69]:
r

array([[ 0,  0,  0, 10, 10, 10],
       [ 0,  0,  0, 10, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

###### It changed the original r array as well , which we should be careful about

In [70]:
r_copy=r.copy()
r_copy

array([[ 0,  0,  0, 10, 10, 10],
       [ 0,  0,  0, 10, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [71]:
r_copy[:]=10
r_copy


array([[10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10]])

In [72]:
r

array([[ 0,  0,  0, 10, 10, 10],
       [ 0,  0,  0, 10, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [73]:
r[:,1:3]

array([[ 0,  0],
       [ 0,  0],
       [ 0,  0],
       [19, 20],
       [25, 26],
       [31, 32]])

 # Iterating over arrays

In [74]:
test=np.random.randint(0,10,(4,3))
test

array([[8, 0, 1],
       [0, 4, 5],
       [7, 6, 9],
       [7, 2, 2]])

In [75]:
for i in test:
    print(i)

[8 0 1]
[0 4 5]
[7 6 9]
[7 2 2]


In [76]:
for i in range(len(test)-1):
    print(test[i][i])

8
4
9


In [77]:
print(range(len(test)))
for i in range(len(test)):
    print(test[:i,1])

range(0, 4)
[]
[0]
[0 4]
[0 4 6]


In [78]:
for i, row in enumerate(test):
    print('row',i,'is',row)

row 0 is [8 0 1]
row 1 is [0 4 5]
row 2 is [7 6 9]
row 3 is [7 2 2]


In [79]:
test2=test**2
test2

array([[64,  0,  1],
       [ 0, 16, 25],
       [49, 36, 81],
       [49,  4,  4]])

In [80]:
for i, j in zip(test, test2):
    print(i,'+',j,'=',i+j)

[8 0 1] + [64  0  1] = [72  0  2]
[0 4 5] + [ 0 16 25] = [ 0 20 30]
[7 6 9] + [49 36 81] = [56 42 90]
[7 2 2] + [49  4  4] = [56  6  6]


In [81]:
help(x.dot)

Help on built-in function dot:

dot(...) method of numpy.ndarray instance
    a.dot(b, out=None)
    
    Dot product of two arrays.
    
    Refer to `numpy.dot` for full documentation.
    
    See Also
    --------
    numpy.dot : equivalent function
    
    Examples
    --------
    >>> a = np.eye(2)
    >>> b = np.ones((2, 2)) * 2
    >>> a.dot(b)
    array([[ 2.,  2.],
           [ 2.,  2.]])
    
    This array method can be conveniently chained:
    
    >>> a.dot(b).dot(b)
    array([[ 8.,  8.],
           [ 8.,  8.]])



In [82]:
a = np.ones([2,2])*3
a

array([[3., 3.],
       [3., 3.]])

In [83]:
b = np.ones((2, 2)) * 2
b

array([[2., 2.],
       [2., 2.]])

In [84]:
c=np.eye(2)
c

array([[1., 0.],
       [0., 1.]])

In [85]:
a.dot(b)  # a.b 

array([[12., 12.],
       [12., 12.]])

In [86]:
a.dot(b).dot(c)

array([[12., 12.],
       [12., 12.]])

In [97]:
import pandas as ps
with open('/Users/nimaarvin/Dropbox/DataScience/Python/Py_Working_Dir/Py_Working_Dir/Applied Data Science with Python - Uni Michigan/Introduction to Data Science in Python/mpg.csv')  as mpg:
    mydata=ps.read_csv(mpg)

In [103]:
mydata.head()

Unnamed: 0 manufacturer model  displ  year  cyl       trans drv  cty  hwy  \
0           1         audi    a4    1.8  1999    4    auto(l5)   f   18   29   
1           2         audi    a4    1.8  1999    4  manual(m5)   f   21   29   
2           3         audi    a4    2.0  2008    4  manual(m6)   f   20   31   
3           4         audi    a4    2.0  2008    4    auto(av)   f   21   30   
4           5         audi    a4    2.8  1999    6    auto(l5)   f   16   26   

  fl    class  
0  p  compact  
1  p  compact  
2  p  compact  
3  p  compact  
4  p  compact

In [114]:
arr=np.array(mydata)
arr

array([[1, 'audi', 'a4', ..., 29, 'p', 'compact'],
       [2, 'audi', 'a4', ..., 29, 'p', 'compact'],
       [3, 'audi', 'a4', ..., 31, 'p', 'compact'],
       ...,
       [232, 'volkswagen', 'passat', ..., 26, 'p', 'midsize'],
       [233, 'volkswagen', 'passat', ..., 26, 'p', 'midsize'],
       [234, 'volkswagen', 'passat', ..., 26, 'p', 'midsize']],
      dtype=object)

In [115]:
arr.shape

(234, 12)

In [116]:
arr.size

2808

In [117]:
arr.dtype

dtype('O')

In [118]:
arr[:,0].dtype

dtype('O')

In [119]:
arr[:,0]

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70,
       71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87,
       88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181,
       182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194,
       195, 196, 197, 198, 199, 200, 201, 202, 

In [120]:
sum(arr[:,0])

27495

In [124]:
np.mean(arr[:,3])

3.4717948717948697

In [125]:
np.median(arr[:,5])

6.0

In [126]:
np.std(arr[:,5])

1.6080873481494262

In [129]:
arr.shape

(234, 12)

In [130]:
arr[arr[:,5]<4].shape

(0, 12)

In [133]:
arr[arr[:,5]<4]

array([], shape=(0, 12), dtype=object)

In [1]:
['a', 'b', 'c'] + [1, 2, 3]

['a', 'b', 'c', 1, 2, 3]

In [2]:
type(lambda x: x+1)

function

In [3]:
import numpy as np

In [4]:
x=np.eye(6)

In [5]:
x

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [7]:
x.reshape(36)[::-7]

array([1., 1., 1., 1., 1., 1.])

In [10]:
x.flatten()[::7]

array([1., 1., 1., 1., 1., 1.])

In [18]:
for i in range(0,6):
        print(x[i,i])

1.0
1.0
1.0
1.0
1.0
1.0


In [21]:
x=np.random.randint(36,size=(6,6))
x

array([[22, 17, 19, 26, 25,  4],
       [28, 25, 13, 11,  6, 29],
       [20,  2, 31,  7,  1, 21],
       [24, 21, 30, 23, 27, 34],
       [19, 23,  5, 23, 13, 16],
       [24, 27,  2,  5,  6, 19]])

In [22]:
x[2:4,2:4]

array([[31,  7],
       [30, 23]])

In [23]:
x[[2,3],[2,3]]

array([31, 23])

In [24]:
import numpy as np
print(np.__version__)

1.15.4


In [25]:
x=np.array([0,1,2,3,4,5,6,7,8,9,10])
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
bo=np.random.randint(2,size=(3,3)).astype(bool)
bo

array([[ True, False,  True],
       [ True,  True, False],
       [False,  True,  True]])

In [41]:
np.full((3,3),True,dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [42]:
np.ones((3,3),dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [45]:
np.zeros((4,4),dtype=bool)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [48]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2!=0]=-1
arr



array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [49]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
arr2=np.copy(arr)
arr2[arr2%2==1]=-1
arr2

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [61]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
arr=np.arange(10)
out=np.where(arr%2==1,0,arr)
out

array([0, 0, 2, 0, 4, 0, 6, 0, 8, 0])

In [63]:
arr.reshape([2,5])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [4]:
import numpy as np
x=np.arange(10)
x.reshape((2,5))


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [11]:
x=np.arange(56)
x.reshape(7,-1)
# setting -1 automatically calculate the number of columns

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [12]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
a
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [17]:
np.stack((a,b))

array([[[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [18]:
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [21]:
np.concatenate((a,b), axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [20]:
np.hstack((a,b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [22]:
np.concatenate((a,b), axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [23]:
a = np.array([1,2,3])

In [30]:
np.concatenate((np.repeat(a,3),a,a,a))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [31]:
np.concatenate((np.repeat(a,3),np.tile(a,3)))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [32]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [34]:
np.intersect1d(a,b) #common items between two array

array([2, 4])

In [35]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [36]:
a-np.intersect1d(a,b)

array([-4, -3, -2, -1,  0])

In [38]:
np.setdiff1d(a,b) #removes all the the items in b that are in a

array([1, 2, 3, 4])

In [39]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [49]:
np.where(a==b) #returns the index of places that the a and b are equal

(array([1, 3, 5, 7]),)

In [50]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [61]:
a[(a>5) & (a<=10)]

array([ 6,  9, 10])

In [64]:
index=np.where((a>=5) & (a<=10))
a[index]

array([ 6,  9, 10])

27

In [69]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max=np.vectorize(maxx)
pair_max(a, b)

array([6, 7, 9, 8, 9, 7, 5])

In [88]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [90]:
arr[:, [1,0,2]]


array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [91]:
arr[:,[2,0,1]]

array([[2, 0, 1],
       [5, 3, 4],
       [8, 6, 7]])

In [92]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [98]:
arr[[1,0,2],:] #swap the rows of an array --very confusing-- you should use the structure of the column header

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [100]:

arr=np.arange(20).reshape(4,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [102]:
arr[[1,0,2,3],:]

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [105]:
arr[:,[1,0,2,3,4]]

array([[ 1,  0,  2,  3,  4],
       [ 6,  5,  7,  8,  9],
       [11, 10, 12, 13, 14],
       [16, 15, 17, 18, 19]])

In [112]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [113]:
arr[::-1,:] # reverse the rows of a 2d array

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [115]:
arr[:,::-1] #reverse the columns of a 2D array

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [126]:
d=np.random.uniform(5,10,size=(5,3))

In [127]:
d

array([[5.9291322 , 8.10754672, 9.20077497],
       [8.06059823, 6.11489262, 6.53815898],
       [7.02154777, 5.16070242, 8.38683631],
       [9.58375954, 6.3013449 , 6.64600435],
       [6.44781815, 5.83261146, 7.34557781]])

In [128]:
np.set_printoptions(threshold=6)

In [130]:
d.flatten()

array([5.9291322 , 8.10754672, 9.20077497, ..., 6.44781815, 5.83261146,
       7.34557781])

In [132]:
np.set_printoptions(threshold=np.nan)

In [133]:
d.flatten()

array([5.9291322 , 8.10754672, 9.20077497, 8.06059823, 6.11489262,
       6.53815898, 7.02154777, 5.16070242, 8.38683631, 9.58375954,
       6.3013449 , 6.64600435, 6.44781815, 5.83261146, 7.34557781])

In [134]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

In [158]:
iris=np.genfromtxt(url,delimiter=',',dtype='object')

In [159]:
iris

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa'],
       [b'5.0', b'3.6', b'1.4', b'0.2', b'Iris-setosa'],
       [b'5.4', b'3.9', b'1.7', b'0.4', b'Iris-setosa'],
       [b'4.6', b'3.4', b'1.4', b'0.3', b'Iris-setosa'],
       [b'5.0', b'3.4', b'1.5', b'0.2', b'Iris-setosa'],
       [b'4.4', b'2.9', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.1', b'1.5', b'0.1', b'Iris-setosa'],
       [b'5.4', b'3.7', b'1.5', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.4', b'1.6', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.0', b'1.4', b'0.1', b'Iris-setosa'],
       [b'4.3', b'3.0', b'1.1', b'0.1', b'Iris-setosa'],
       [b'5.8', b'4.0', b'1.2', b'0.2', b'Iris-setosa'],
       [b'5.7', b'4.4', b'1.5', b'0.4', b'Iris-setosa'],
       [b'5.4', b'3.9', b'1.3', b'0.4', b'Iris-setosa'],
       [b'5.1', b'3.5', b'1.4',

In [160]:
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [161]:
iris

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa'],
       [b'5.0', b'3.6', b'1.4', b'0.2', b'Iris-setosa'],
       [b'5.4', b'3.9', b'1.7', b'0.4', b'Iris-setosa'],
       [b'4.6', b'3.4', b'1.4', b'0.3', b'Iris-setosa'],
       [b'5.0', b'3.4', b'1.5', b'0.2', b'Iris-setosa'],
       [b'4.4', b'2.9', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.1', b'1.5', b'0.1', b'Iris-setosa'],
       [b'5.4', b'3.7', b'1.5', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.4', b'1.6', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.0', b'1.4', b'0.1', b'Iris-setosa'],
       [b'4.3', b'3.0', b'1.1', b'0.1', b'Iris-setosa'],
       [b'5.8', b'4.0', b'1.2', b'0.2', b'Iris-setosa'],
       [b'5.7', b'4.4', b'1.5', b'0.4', b'Iris-setosa'],
       [b'5.4', b'3.9', b'1.3', b'0.4', b'Iris-setosa'],
       [b'5.1', b'3.5', b'1.4',

In [162]:
len(iris)

150

In [163]:
iris.shape

(150, 5)

In [164]:
iris.size

750

In [165]:
iris[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

In [168]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
print(iris_1d.shape)

# Solution:
species = np.array([row[4] for row in iris_1d])
species[:5]

(150,)


/Users/nimaarvin/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  


array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa'], dtype='|S18')

In [169]:
species.shape

(150,)

In [170]:
species[:5]

array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa'], dtype='|S18')